### ISSUE TITLE
[Bug] 能否支持给多个用户发邮件告警

### ISSUE THREAD

**Issue by fuleru** [zdz/ServerStatus-Rust#297]
### Checklist

- [X] 我已经将版本更新到最新 Release 版
- [X] 我已经详细阅读文档, 仍然无法解决
- [X] 我已经搜索已有的 Issues | Discussions, 仍然无法解决
- [X] 我已经尝试过 Google 搜索仍然无法解决

### 💻 系统环境

Ubuntu

### 🐛 问题描述

to = "xxxxblinux@gmail.com yyyblinux@gmail.com"

# ./stat_server -c config.toml --notify-test
然后直接core dump了

send test message to email
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUser', server/src/notifier/email.rs:53:40
stack backtrace:
   0:     0x7fe003cbe630 - <unknown>
   1:     0x7fe003a7388e - <unknown>
   2:     0x7fe003c9c514 - <unknown>
   3:     0x7fe003cbfb8f - <unknown>
   4:     0x7fe003cbf78f - <unknown>
   5:     0x7fe003cc07f9 - <unknown>
   6:     0x7fe003cc02d4 - <unknown>
   7:     0x7fe003cc0236 - <unknown>
   8:     0x7fe003cc0221 - <unknown>
   9:     0x7fe003945b72 - <unknown>
  10:     0x7fe003945ef2 - <unknown>
  11:     0x7fe00398746a - <unknown>
  12:     0x7fe0039e9185 - <unknown>
  13:     0x7fe0039f363f - <unknown>
  14:     0x7fe003a19974 - <unknown>
  15:     0x7fe003a0cbb6 - <unknown>
  16:     0x7fe0039769a6 - <unknown>
  17:     0x7fe0039774c1 - <unknown>
  18:     0x7fe003a1e1f8 - <unknown>
Aborted (core dumped)

### 🚦 期望结果

能支持给多个邮件地址告警

**Comment by fuleru** [comment]
使用的是英文逗号分隔，也是失败了。

send test message to email
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidUser', server/src/notifier/email.rs:53:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

**Comment by fuleru** [comment]
好的，感谢！
